### PR TITLE
Prefer Clone to Copy. Fixes #74.

### LINKED ISSUE #74: token and SliceStream do not play together well
First, thanks for the library.  It's a fun way to learn Rust!

I'd like to understand some of the API decisions the library makes.  First, my motivating use case is to parse a token stream (not a character stream), and my token's do not implement `Copy` because they include `String` data, like:
```
struct Token {
    Keyword(String),
    ...
}
```

If I use `SliceStream`, I can parse `&[Token]`.  However, I can't really use `token`, because the `Item` type of `SliceStream` is `&'a Token` and that's not something I can create with the correct lifetime.  It seems to me like `token` should have `where Item : Clone` and explicitly `.clone()` it's argument.  I see at https://github.com/Marwes/combine/blob/master/src/combinator.rs#L200 that we can't actually _parse_ without `Item : Clone`.

Is this deliberate?  Oversight?  Am I using `SliceStream` incorrectly?

### PR DESCRIPTION
**Pull request by ncalexan**
Together, these commits address the cases I asked about in #74 and #75.  With these, `SliceStream` consumers can use `token()`; and consumers who want a `T` item type can parse non-`Copy` tokens.

### CODE REVIEW

File: src/combinator.rs [hunk 1]
```diff
@@ -189,7 +189,7 @@ pub fn satisfy_map<I, P, R>(predicate: P) -> SatisfyMap<I, P>
 #[derive(Clone)]
 pub struct Token<I>
     where I: Stream,
-          I::Item: PartialEq
+          I::Item: PartialEq + Clone,
```
Comment (Marwes) [inline src/combinator.rs]: This bound and then one below it is not necessary.

File: src/combinator.rs [hunk 2]
```diff
@@ -225,10 +225,10 @@ impl<I> Parser for Token<I>
 #[inline(always)]
 pub fn token<I>(c: I::Item) -> Token<I>
     where I: Stream,
-          I::Item: PartialEq
+          I::Item: PartialEq + Clone,
 {
     Token {
-        c: c,
+        c: c.clone(),
```
Comment (Marwes) [inline src/combinator.rs]: This clone is not necessary

File: src/combinator.rs [hunk 3]
```diff
@@ -225,10 +225,10 @@ impl<I> Parser for Token<I>
 #[inline(always)]
 pub fn token<I>(c: I::Item) -> Token<I>
     where I: Stream,
-          I::Item: PartialEq
+          I::Item: PartialEq + Clone,
```
Comment (Marwes) [inline src/combinator.rs]: Unnecessary bound

**Comment by Marwes** [comment]
Nice! Thanks!, I originally limited the `[T]` stream to `T; Copy` since a `Clone` bound turned out be more expensive but running the benchmarks on this PR showed no difference anymore so it looks like codegen has improved.

**Comment by ncalexan** [comment]
@Marwes thanks for the quick response.  I turned the last commit into a test-only change.  Is there anything else you want in order to merge?

**Comment by Marwes** [comment]
Nope, looks good now. Published to crates.io as 2.1.1.
